const paisCapital = new Map();

paisCapital.set('Anguila', 'The Valley');
paisCapital.set('Antigua y Barbuda', 'Saint John’s');
paisCapital.set('Argentina', 'Buenos Aires');
paisCapital.set('Aruba', 'Oranjestad');
paisCapital.set('Bahamas', 'Nassau');
paisCapital.set('Barbados', 'Bridgetown');
paisCapital.set('Belice', 'Belmopan');
paisCapital.set('Bermudas', 'Hamilton');
paisCapital.set('Bolivia', 'Sucre');
paisCapital.set('Brasil', 'Brasília');
paisCapital.set('Canadá', 'Ottawa');
paisCapital.set('Chile', 'Santiago');
paisCapital.set('Colombia', 'Bogotá');
paisCapital.set('Costa Rica', 'San José');
paisCapital.set('Cuba', 'la Habana');
paisCapital.set('Curaçao', 'Willemstad');
paisCapital.set('Dominica', 'Roseau');
paisCapital.set('Ecuador', 'Quito');
paisCapital.set('El Salvador', 'San Salvador');
paisCapital.set('Estados Unidos', 'Washington, D.C.');
paisCapital.set('Georgia del Sur y las Islas Sandwich del Sur', 'King Edward Point');
paisCapital.set('Granada', "Saint George's");
paisCapital.set('Groenlandia', 'Nuuk');
paisCapital.set('Guadalupe', 'Basse-Terre');
paisCapital.set('Guatemala', 'Ciudad de Guatemala');
paisCapital.set('Guayana', 'Georgetown');
paisCapital.set('Guayana Francesa', 'Cayenne');
paisCapital.set('Haití', 'Port-au-Prince');
paisCapital.set('Honduras', 'Tegucigalpa');
paisCapital.set('Isla de San Martín', 'Marigot');
paisCapital.set('Islas Caimán', 'George Town');
paisCapital.set('Islas Malvinas', 'Stanley');
paisCapital.set('Islas Turcas y Caicos', 'Cockburn Town');
paisCapital.set('Islas Vírgenes (UK)', 'Road Town');
paisCapital.set('Islas Vírgenes Americanas', 'Charlotte Amalie');
paisCapital.set('Jamaica', 'Kingston');
paisCapital.set('Martinica', 'Fort-de-France');
paisCapital.set('México', 'Ciudad de México');
paisCapital.set('Montserrat', 'Brades');
paisCapital.set('Nicaragua', 'Managua');
paisCapital.set('Panamá', 'Ciudad de Panama');
paisCapital.set('Paraguay', 'Asunción');
paisCapital.set('Perú', 'Lima');
paisCapital.set('Puerto Rico', 'San Juan');
paisCapital.set('República Dominicana', 'Santo Domingo');
paisCapital.set('San Bartolomé', 'Gustavia');
paisCapital.set('San Cristóbal y Nieves', 'Basseterre');
paisCapital.set('San Pedro y Miquelón', 'Saint-Pierre');
paisCapital.set('San Vicente y las Granadinas', 'Kingstown');
paisCapital.set('Santa Lucía', 'Castries');
paisCapital.set('Sint Maarten', 'Philipsburg');
paisCapital.set('Surinam', 'Paramaribo');
paisCapital.set('Trinidad y Tobago', 'Port-of-Spain');
paisCapital.set('Uruguay', 'Montevideo');
paisCapital.set('Venezuela', 'Caracas');
paisCapital.set('Albania', 'Tirana');
paisCapital.set('Alemania', 'Berlín');
paisCapital.set('Andorra', 'Andorra la Vella');
paisCapital.set('Austria', 'Viena');
paisCapital.set('Bailía de Guernsey', 'Saint Peter Port');
paisCapital.set('Belarús', 'Minsk');
paisCapital.set('Bélgica', 'Bruselas');
paisCapital.set('Bosnia y Hercegovina', 'Sarajevo');
paisCapital.set('Bulgaria', 'Sofía');
paisCapital.set('Chequia', 'Praga');
paisCapital.set('Ciudad del Vaticano', 'Ciudad del Vaticano');
paisCapital.set('Croacia', 'Zagreb');
paisCapital.set('Dinamarca', 'Copenhague');
paisCapital.set('Eslovaquia', 'Bratislava');
paisCapital.set('Eslovenia', 'Ljubljana');
paisCapital.set('España', 'Madrid');
paisCapital.set('Estonia', 'Tallinn');
paisCapital.set('Finlandia', 'Helsinki');
paisCapital.set('Francia', 'París');
paisCapital.set('Gibraltar', 'Gibraltar');
paisCapital.set('Grecia', 'Athens');
paisCapital.set('Hungría', 'Budapest');
paisCapital.set('Irlanda', 'Dublin');
paisCapital.set('Isla de Man', 'Douglas');
paisCapital.set('Islandia', 'Reykjavík');
paisCapital.set('Islas Åland', 'Mariehamn');
paisCapital.set('Islas Feroe', 'Tórshavn');
paisCapital.set('Italia', 'Roma');
paisCapital.set('Jersey', 'Saint Helier');
paisCapital.set('Kosovo', 'Pristina');
paisCapital.set('Letonia', 'Riga');
paisCapital.set('Liechtenstein', 'Vaduz');
paisCapital.set('Lituania', 'Vilnius');
paisCapital.set('Luxemburgo', 'Luxembourg');
paisCapital.set('Macedonia del Norte', 'Skopje');
paisCapital.set('Malta', 'Valletta');
paisCapital.set('Moldavia', 'Chisinau');
paisCapital.set('Montenegro', 'Podgorica');
paisCapital.set('Noruega', 'Oslo');
paisCapital.set('Países Bajos', 'Ámsterdam');
paisCapital.set('Polonia', 'Varsovia');
paisCapital.set('Portugal', 'Lisbon');
paisCapital.set('Principado de Mónaco', 'Monaco');
paisCapital.set('Reino Unido', 'Londres');
paisCapital.set('Rumania', 'Bucarest');
paisCapital.set('Rusia', 'Moscú');
paisCapital.set('San Marino', 'San Marino');
paisCapital.set('Serbia', 'Belgrado');
paisCapital.set('Suecia', 'Estocolmo');
paisCapital.set('Suiza', 'Bern');
paisCapital.set('Svalbard y Jan Mayen', 'Longyearbyen');
paisCapital.set('Ucrania', 'Kiev');
paisCapital.set('Afganistán', 'Kabul');
paisCapital.set('Arabia Saudita', 'Riyadh');
paisCapital.set('Armenia', 'Ereván');
paisCapital.set('Azerbaiyán', 'Baku');
paisCapital.set('Bahrein', 'Manama');
paisCapital.set('Bangladesh', 'Dhaka');
paisCapital.set('Brunéi', 'Bandar Seri Begawan');
paisCapital.set('Bután', 'Thimphu');
paisCapital.set('Cambodia', 'Phnom Penh');
paisCapital.set('Catar', 'Doha');
paisCapital.set('China', 'Pekín');
paisCapital.set('Chipre', 'Nicosia');
paisCapital.set('Corea del Norte', 'Pyongyang');
paisCapital.set('Corea del Sur', 'Seúl');
paisCapital.set('Emiratos Árabes Unidos', 'Abu Dhabi');
paisCapital.set('Filipinas', 'Manila');
paisCapital.set('Georgia', 'Tiflis');
paisCapital.set('Hong Kong', 'Hong Kong');
paisCapital.set('India', 'New Delhi');
paisCapital.set('Indonesia', 'Jacarta');
paisCapital.set('Irán', 'Teherán');
paisCapital.set('Iraq', 'Bagdad');
paisCapital.set('Israel', 'Jerusalén');
paisCapital.set('Japón', 'Tokio');
paisCapital.set('Jordania', 'Amman');
paisCapital.set('Kazajstán', 'Nursultan');
paisCapital.set('Kirguistán', 'Bishkek');
paisCapital.set('Kuwait', 'Ciudad de Kuwait');
paisCapital.set('Laos', 'Vientiane');
paisCapital.set('Líbano', 'Beirut');
paisCapital.set('Macao', 'Concelho de Macao');
paisCapital.set('Malasia', 'Kuala Lumpur');
paisCapital.set('Maldivas', 'Malé');
paisCapital.set('Mongolia', 'Ulaanbaatar');
paisCapital.set('Myanmar', 'Nay Pyi Taw');
paisCapital.set('Nepal', 'Kathmandu');
paisCapital.set('Omán', 'Muscat');
paisCapital.set('Pakistán', 'Islamabad');
paisCapital.set('Palestina', 'Ramallah');
paisCapital.set('Singapur', 'Singapur');
paisCapital.set('Siria', 'Damasco');
paisCapital.set('Sri Lanka', 'Colombo');
paisCapital.set('Tailandia', 'Bangkok');
paisCapital.set('Taiwán', 'Taipei');
paisCapital.set('Tayikistán', 'Dushanbe');
paisCapital.set('Timor Oriental', 'Dili');
paisCapital.set('Turkmenistán', 'Ashgabat');
paisCapital.set('Turquía', 'Ankara');
paisCapital.set('Uzbekistán', 'Tashkent');
paisCapital.set('Vietnam', 'Hanoi');
paisCapital.set('Yemen', 'Sanaa');
paisCapital.set('Australia', 'Canberra');
paisCapital.set('Isla de Navidad', 'Flying Fish Cove');
paisCapital.set('Isla Norfolk', 'Kingston');
paisCapital.set('Islas Cocos', 'West Island');
paisCapital.set('Nueva Zelandia', 'Wellington');
paisCapital.set('Fiji', 'Suva');
paisCapital.set('Guam', 'Hagåtña');
paisCapital.set('Islas Cook', 'Avarua');
paisCapital.set('Islas Marianas del Norte', 'Saipan');
paisCapital.set('Islas Marshall', 'Majuro');
paisCapital.set('Islas Pitcairn', 'Adamstown');
paisCapital.set('Islas Salomón', 'Honiara');
paisCapital.set('Kiribati', 'Tarawa');
paisCapital.set('Nauru', 'Yaren');
paisCapital.set('Niue', 'Alofi');
paisCapital.set('Nueva Caledonia', 'Nouméa');
paisCapital.set('Papúa Nueva Guinea', 'Port Moresby');
paisCapital.set('Polinesia Francesa', 'Papeete');
paisCapital.set('Samoa', 'Apia');
paisCapital.set('Samoa Americana', 'Pago Pago');
paisCapital.set('Tonga', 'Nuku‘alofa');
paisCapital.set('Tuvalu', 'Funafuti');
paisCapital.set('Vanuatu', 'Port-Vila');
paisCapital.set('Wallis y Futuna', 'Mata-Utu');
paisCapital.set('Angola', 'Luanda');
paisCapital.set('Argelia', 'Argel');
paisCapital.set('Benín', 'Porto-Novo');
paisCapital.set('Botsuana', 'Gaborone');
paisCapital.set('Burkina Faso', 'Ouagadougou');
paisCapital.set('Burundi', 'Bujumbura');
paisCapital.set('Cabo Verde', 'Praia');
paisCapital.set('Camerún', 'Yaundé');
paisCapital.set('Chad', "N'Djamena");
paisCapital.set('Comores', 'Moroni');
paisCapital.set('Congo', 'Brazzaville');
paisCapital.set('Costa de Marfil', 'Yamoussoukro');
paisCapital.set('Egipto', 'Cairo');
paisCapital.set('Eritrea', 'Asmara');
paisCapital.set('Esuatini', 'Mbabane');
paisCapital.set('Etiopía', 'Addis Ababa');
paisCapital.set('Gabón', 'Libreville');
paisCapital.set('Gambia', 'Banjul');
paisCapital.set('Ghana', 'Accra');
paisCapital.set('Guinea', 'Conakry');
paisCapital.set('Guinea Ecuatorial', 'Malabo');
paisCapital.set('Guinea-Bissau', 'Bissau');
paisCapital.set('Isla Mauricio', 'Port Louis');
paisCapital.set('Kenia', 'Nairobi');
paisCapital.set('Lesotho', 'Maseru');
paisCapital.set('Liberia', 'Monrovia');
paisCapital.set('Libia', 'Trípoli');
paisCapital.set('Madagascar', 'Antananarivo');
paisCapital.set('Malaui', 'Lilongwe');
paisCapital.set('Malí', 'Bamako');
paisCapital.set('Marruecos', 'Rabat');
paisCapital.set('Mauritania', 'Nouakchott');
paisCapital.set('Mayotte', 'Mamoudzou');
paisCapital.set('Mozambique', 'Maputo');
paisCapital.set('Namibia', 'Windhoek');
paisCapital.set('Níger', 'Niamey');
paisCapital.set('Nigeria', 'Abuja');
paisCapital.set('República Centroafricana', 'Bangui');
paisCapital.set('República Democrática del Congo', 'Kinshasa');
paisCapital.set('Reunión', 'Saint-Denis');
paisCapital.set('Ruanda', 'Kigali');
paisCapital.set('Sáhara Occidental', 'El Aaiún');
paisCapital.set('Santa Elena, Ascensión y Tristán de Acuña', 'Jamestown');
paisCapital.set('Santo Tomé y Príncipe', 'São Tomé');
paisCapital.set('Senegal', 'Dakar');
paisCapital.set('Seychelles', 'Victoria');
paisCapital.set('Sierra Leona', 'Freetown');
paisCapital.set('Somalia', 'Mogadishu');
paisCapital.set('Sudáfrica', 'Pretoria');
paisCapital.set('Sudán', 'Khartoum');
paisCapital.set('Sudán del Sur', 'Juba');
paisCapital.set('Tanzania', 'Dodoma');
paisCapital.set('Togo', 'Lomé');
paisCapital.set('Túnez', 'Túnez');
paisCapital.set('Uganda', 'Kampala');
paisCapital.set('Yibuti', 'Djibouti');
paisCapital.set('Zambia', 'Lusaka');
paisCapital.set('Zimbabue', 'Harare');
